### ISSUE TITLE
Brain cropping fails with dynamic datasets

### ISSUE THREAD

**Issue by DariaFerrara** [QIMP-Team/MOOSE#38]
The following error occurred after using Moose with dynamic datasets of Vision lung cancer patients. All other segmentations and SUV extraction properly worked. No error occurred after re-running Moose with the corresponding static dataset. 

```
Brain found in field-of-view of PET/CT data...                         
- Cropping brain from PET image using the aligned CT brain mask
Traceback (most recent call last):
  File "/usr/local/bin/moose", line 215, in <module>
    cropped_pet_brain = iop.crop_image_using_mask(image_to_crop=pet_file[0],
  File "/home/mz/Documents/Softwares/MOOSE/src/imageOp.py", line 237, in crop_image_using_mask
    out_of_bounds = upper_bounds >= img_dim
ValueError: operands could not be broadcast together with shapes (3,) (4,)
```

**Comment by Keyn34** [comment]
It looks like the error occurs due to the dimension mismatch with the PET image. Just discarding the fourth dimension should resolve that issue ***if*** 4D data is a legit input for MOOSE.

**Comment by LalithShiyam** [comment]
Guys, this is a duplicate issue. Closing it. Refer the previous issue here: https://github.com/QIMP-Team/MOOSE/issues/30
