### ISSUE TITLE
BUG: sitk::ERROR: The file MOOSE-Split-unified-PET-CT-atlas.nii.gz does not exist.

### ISSUE THREAD

**Issue by chris-clem** [QIMP-Team/MOOSE#46]
Hi,

I am trying to run MOOSE on a bunch of patients with whole-body CTs. For two of the patient, MOOSE fails with the following error

```
✔ Segmented psoas from /home/user/Data/....IMA_0000.nii.gz                                              
- Conducting automatic error analysis in similarity space for: /home/user/Data/.../labels/MOOSE-Non-cerebral-tissues-CT-....nii.gz
Traceback (most recent call last):
  File "/usr/local/bin/moose", line 139, in <module>                                                                                                                                                        
    ea.similarity_space(ct_atlas, sim_space_dir, segmentation_error_stats)                                                                                                                                         
  File "/home/user/Code/MOOSE/src/errorAnalysis.py", line 147, in similarity_space
    shape_parameters = iop.get_shape_parameters(split_atlas)
  File "/home/user/Code/MOOSE/src/imageOp.py", line 86, in get_shape_parameters
    label_img = SimpleITK.Cast(SimpleITK.ReadImage(label_image), SimpleITK.sitkInt32)
  File "/home/user/miniconda3/envs/moose/lib/python3.9/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/home/user/miniconda3/envs/moose/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "/home/user/Data/.../labels/sim_space/similarity-space/MOOSE-Split-unified-PET-CT-atlas.nii.gz" does not exist.
```

Do you know what could be the problem if the file not existing? It works for the other patients.

**Comment by LalithShiyam** [comment]
Hi @chris-clem, is it just a couple of patients where it fails? If yes, would it be ok for you to send the anon data? I can have a look at the patients...it's hard for me to tell what exactly went wrong without running it myself. Would that be a reasonable request?

**Comment by LalithShiyam** [comment]
@chris-clem any luck?

**Comment by chris-clem** [comment]
Hey, sorry, I cannot share the patient data. I will have a look at the patient data with a colleague. Maybe we find something weird.

Do you have a rough idea of what might be causing this?

**Comment by LalithShiyam** [comment]
@chris-clem is this solved or figured out? If yes can I close this issue?

**Comment by chris-clem** [comment]
Yes, you can close it for now
