### ISSUE TITLE
BUG: IndexError: list index out of range

### ISSUE THREAD

**Issue by gsdgui** [QIMP-Team/MOOSE#49]
I am running MOOSE in a patient folder with two subfolders for CT and PET under DCIOM format. However, I am getting this error message:
✔ Segmented abdominal organs from /data/111111111/CT/1.2.156.112605.189250954672781.211222004834.3.9684.76929_0000.nii.gz
✔ Segmented Bones from /data/111111111/CT/1.2.156.112605.189250954672781.211222004834.3.9684.76929_0000.nii.gz
✔ Segmented skeletal muscle, subcutaneous and visceral fat from /data/111111111/CT/1.2.156.112605.189250954672781.211222004834.3.9684.76929_0000.nii.g  z
✔ Segmented psoas from /data/111111111/CT/1.2.156.112605.189250954672781.211222004834.3.9684.76929_0000.nii.gz
Traceback (most recent call last):
  File "/usr/local/bin/moose", line 140, in <module>
    ct_atlas = ie.segment_ct_3mm(ct_file[0], out_dir)
  File "/MOOSE/src/inferenceEngine.py", line 427, in segment_ct_3mm
    logging.info(f"Non-cerebral tissues segmented and saved in {fop.get_files(out_dir, 'MOOSE*CT*nii.gz')[0]}")
IndexError: list index out of range

I debugged as follows but didn't get the results I should have.  The function sum_image_stack() does not seem to work.：
>>> from imageOp import sum_image_stack
>>> sum_image_stack("/data/111111111/labels", "*nii.gz", "/data/111111111/labels/all.nii.gz")
Sum image stack!!!
current work path:  /data/111111111/labels
wild_card:  *nii.gz
out_img:  /data/111111111/labels/all.nii.gz
list of current dir path:  ['sim_space', 'plans.pkl', 'Organs_1.2.156.112605.189250954672781.211222005615.4.16884.16127.dcm.nii.gz', 'Bones_1.2.156.112605.189250954672781.211222005615.4.16884.16127.dcm.nii.gz', 'Fat-Muscle_1.2.156.112605.189250954672781.211222005615.4.16884.16127.dcm.nii.gz', 'Psoas_1.2.156.112605.189250954672781.211222005615.4.16884.16127.dcm.nii.gz']
cmd: c3d *nii.gz -accum -add -endaccum -o /data/111111111/labels/all\.nii\.gz
finish!

There are any suggestion？
Thanks.

**Comment by LalithShiyam** [comment]
Hi there, is this the only patient where it fails?

**Comment by gsdgui** [comment]
Actually, I just tested the one patient.

**Comment by LalithShiyam** [comment]
Hi again, it’s hard for me to tell why it fails. Would you be open to share an anonym data? So that I can come up with a concrete response?

**Comment by gsdgui** [comment]
I might be able to give you the data tomorrow. I think there is something wrong with the function sum_image_stack. Can you share the source code about c3d?

**Comment by gsdgui** [comment]
I get it. You are right, there is nothing wrong with the code, it's the problem with the sh file permissions. Thank you very much for the reply.
