### ISSUE TITLE
moosez running properly on one of my pc, but not in another one

### ISSUE THREAD

**Issue by HyperionCore** [QIMP-Team/MOOSE#78]
I use the latest moosez version.

I have 2 computers, one is Dell 7960, with 512GB RAM, and 2 A6000 GPU, Ubuntu 20.4 LTS, in the terminal, moosez running properly,

but for another computer Dell 5820, with 256GB RAM, and 1 1080ti GPU, Ubuntu 22.04 LTS: the GPU is working fine for other program, but not for moosez, as shown in below, CUDA detection is OK, but problem occurs at postprocessing stage, it cannot find the segmentation nifty file,  if I forcedly change the device to CPU, it works fine, I try to update the GPU driver to 545, still not work for gpu.  any idea what the problem could be, thanks a lot.

############################################################################
CUDA is available on this device with 1 GPU(s). Predictions will be run on GPU.

 🌐 MODEL DOWNLOAD:

 A local instance of Dataset123_Organs has been detected. 

 🔍 STANDARDIZING INPUT DATA TO NIFTI:

 Processing s1... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
 Standardization complete.
 Number of moose compliant subjects: 1 out of 1 

 🔮 PREDICT:

⠦ [1/1] Preparing data for prediction for s1.../home/hyperion/PycharmProjects/moosedata/Falcon1/s1/moosez-clin_ct_organs-2023-10-31-21-28-59/CT
⠋ [1/1] Running prediction for s1 using clin_ct_organs...original_image_files[0] /home/hyperion/PycharmProjects/moosedata/Falcon1/s1/moosez-clin_ct_organs-2023-10-31-21-28-59/CT/CT_3_standard_375_0000.nii.gz
Traceback (most recent call last):
  File "/home/hyperion/anaconda3/envs/moosez/bin/moosez", line 8, in <module>
    sys.exit(main())
  File "/home/hyperion/anaconda3/envs/moosez/lib/python3.9/site-packages/moosez/moosez.py", line 201, in main
    predict.predict(model_name, input_dir, output_dir, accelerator)
  File "/home/hyperion/anaconda3/envs/moosez/lib/python3.9/site-packages/moosez/predict.py", line 80, in predict
    postprocess(original_image_files[0], output_dir, model_name)
  File "/home/hyperion/anaconda3/envs/moosez/lib/python3.9/site-packages/moosez/predict.py", line 133, in postprocess
    predicted_image = file_utilities.get_files(output_dir, '.nii.gz')[0]
IndexError: list index out of range

**Comment by LalithShiyam** [comment]
Hi @HyperionCore, thanks for the elaborate message. I think the error occurs because there is no segmentation being predicted. On top of my head, I think it is the issue with python version. Can you update it to python3.10? Right now I see its 3.9. I assume you use 2.2.38 when you say latest version of moose. Kindly try it with the right python version and let me know how it pans out.
Cheers,
Lalith

**Comment by HyperionCore** [comment]
thanks for the help! let me check the python and update it

**Comment by LalithShiyam** [comment]
Great, P.S: You don't need 256 GB RAM anymore. moosev2 is quite lean. Keep me posted.

**Comment by HyperionCore** [comment]
I set up a new env, python version is 3.10, but seems the same result, then I tried to switch the OS to win10 for the same computer, it works fine.

CUDA is available on this device with 1 GPU(s). Predictions will be run on GPU.

 🌐 MODEL DOWNLOAD:

 A local instance of Dataset123_Organs has been detected. 

 🔍 STANDARDIZING INPUT DATA TO NIFTI:

 Processing s1... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
 Standardization complete.
 Number of moose compliant subjects: 1 out of 1 

 🔮 PREDICT:

⠸ [1/1] Running prediction for s1 using clin_ct_organs...Traceback (most recent call last):
  File "/home/hyperion/anaconda3/envs/moose/bin/moosez", line 8, in <module>
    sys.exit(main())
  File "/home/hyperion/anaconda3/envs/moose/lib/python3.10/site-packages/moosez/moosez.py", line 201, in main
    predict.predict(model_name, input_dir, output_dir, accelerator)
  File "/home/hyperion/anaconda3/envs/moose/lib/python3.10/site-packages/moosez/predict.py", line 78, in predict
    postprocess(original_image_files[0], output_dir, model_name)
  File "/home/hyperion/anaconda3/envs/moose/lib/python3.10/site-packages/moosez/predict.py", line 131, in postprocess
    predicted_image = file_utilities.get_files(output_dir, '.nii.gz')[0]
IndexError: list index out of range

**Comment by LalithShiyam** [comment]
@Keyn34 and @mprires Did you guys encounter such errors before?
Is it related to the torch issue?

@HyperionCore so it works in windows but not in linux?

**Comment by Keyn34** [comment]
@HyperionCore, out of curiosity, can you try to set up a virtual environment without anaconda?

**Comment by LalithShiyam** [comment]
@HyperionCore can you please try it using regular python venv without conda. Just to be sure. We have never tested it in a conda env. Would be nice to see if it works on a regular python venv. Sorry about the trouble.

**Comment by HyperionCore** [comment]
> @Keyn3他和4 and @mprires Did you guys encounter such errors before? Is it related to the torch issue?
> 
> @HyperionCore so it works in windows but not in linux?

thanks for the help @LalithShiyam @Keyn34 ! yes, it works on win10, but not in ubuntu.   I checked the torch also, by using torch.cuda.is_available(), returns true, then I make a test to use GPU to run other inferencing, it works fine.

and in win10 and my another ubuntu computer, both use anaconda env, all works fine, I guess it has sth to do with environment  or sth else,  want to do troubleshooting.

because the error occurs at the postprocessing stage, I'm wondering how to let the program give error exception before post processing, looks like the prediction is not complete or some codes are skipped during running, I think.

**Comment by LalithShiyam** [comment]
@HyperionCore I think the nnunet prediction is not done. Would you be kind enough to confirm that there is no segmentation/json file in the output_dir. I am pretty confident, that its the prediction. Usually the prediction fails when the environment variables are not seen or the chunking of the large CT volume is not done by `dask`.

As a 'good' news, it works in every computer of yours other than the one that you are trying? Am i right?

**Comment by HyperionCore** [comment]
yes, it works fine for both computers, I checked the data generated during processing.

1. the moosez-clin_ct_organs-2023-10-31-22-22-40 folder created;
2. CT, segmentations, stats folders created;
3. in CT folder, there are CT_3_standard_375_0000.nii.gz and temp folder, in temp folder, there are chunk01_0000.nii.gz and chunk02_0000.nii.gz, chunk03_0000.nii.gz
4. in segmentation, there are 3 files, dataset.json, plans.json, predict_from_raw_data_args.json, (if prediction done, there should be also a nifty file)
5. in stats folder, it's empty

and I monitor the nvidia-smi every 1 second, there is no change of the memory and power usage change, before I guess maybe the GPU receive the job and terminate quickly, but seems no work was sent to it.

**Comment by LalithShiyam** [comment]
OK, this is super strange. The prediction has been initiated, but only there is no segmentation. We haven't encountered anything like this before. 

We will try to reproduce the error and keep you posted.

**Comment by HyperionCore** [comment]
thanks! and log for the refence(I paste the last portion of the log file, after RUNNING PREDICTION, it's empty):

2023-10-31 22:22:39,008 INFO     [convert_dir.py:79] --------------------------------------------
2023-10-31 22:22:39,008 INFO     [convert_dir.py:80] Start converting 12_tk_qclear_450_ddg
2023-10-31 22:22:39,008 INFO     [convert_dicom.py:180] WARNING: Assuming generic vendor conversion (ANATOMICAL)
2023-10-31 22:22:39,293 INFO     [convert_generic.py:164] Saving nifti to disk /home/hyperion/PycharmProjects/moosedata/Falcon1/s1/12_tk_qclear_450_ddg.nii
2023-10-31 22:22:40,547 INFO     [moosez.py:140]  Standardization complete.
2023-10-31 22:22:40,547 INFO     [input_validation.py:63]  Number of moose compliant subjects: 1 out of 1
2023-10-31 22:22:40,547 INFO     [moosez.py:163]  
2023-10-31 22:22:40,547 INFO     [moosez.py:164]  PERFORMING PREDICTION:
2023-10-31 22:22:40,547 INFO     [moosez.py:165]  
2023-10-31 22:22:40,548 INFO     [moosez.py:174]  
2023-10-31 22:22:40,548 INFO     [moosez.py:175] [38;5;141m SETTING UP MOOSE-Z DIRECTORY:[0m
2023-10-31 22:22:40,548 INFO     [moosez.py:177]  
2023-10-31 22:22:40,548 INFO     [moosez.py:180]  MOOSE directory for subject s1 at: /home/hyperion/PycharmProjects/moosedata/Falcon1/s1/moosez-clin_ct_organs-2023-10-31-22-22-40
2023-10-31 22:22:44,141 INFO     [moosez.py:190]  [38;5;40mData preparation complete using clin_ct_organs for subject s1[0m
2023-10-31 22:22:44,141 INFO     [moosez.py:195]  
2023-10-31 22:22:44,141 INFO     [moosez.py:196]  RUNNING PREDICTION:
2023-10-31 22:22:44,141 INFO     [moosez.py:197]

**Comment by LalithShiyam** [comment]
OK, but it doesn't tell a lot. I need to add some useful patch to tell if something breaks.

**Comment by HyperionCore** [comment]
another problem, when I run the code in pycharm, there is error:

from moosez import moose

model_name = 'clin_ct_organs'
input_dir = r'D:\moosez\img\Falcon1'
output_dir = r'D:\moosez\img'
accelerator = 'gpu'
moose(model_name, input_dir, output_dir, accelerator)

######################################
File "C:\Users\sduha\anaconda3\envs\moosez\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
#####################################################

looks like sth wrong with multiprocessing module, i modified code like below, but still not work

from moosez import moose
from multiprocessing import freeze_support

model_name = 'clin_ct_organs'
input_dir = r'D:\moosez\img\Falcon1'
output_dir = r'D:\moosez\img'
accelerator = 'gpu'
moose(model_name, input_dir, output_dir, accelerator)

if __name__ == '__main__':
    freeze_support()

**Comment by HyperionCore** [comment]
after I modified code again, the error was gone:

from moosez import moose
from multiprocessing import freeze_support

def main():
    model_name = 'clin_ct_organs'
    input_dir = r'D:\moosez\img\Falcon1'
    output_dir = r'D:\moosez\img'
    accelerator = 'cuda'
    moose(model_name, input_dir, output_dir, accelerator)

if __name__ == '__main__':
    freeze_support()
    main()

but therer is other issue:

 raise ImageFileError(f'Cannot work out file type of "{filename}"')
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "D:\moosez\img\Falcon1\S1"

the folder working fine in terminal mode, but not work in pycharm

**Comment by LalithShiyam** [comment]
Hi @HyperionCore,
Are you trying to use moose as a library and feeding a bunch of subjects? When using moose as a library, it can just take in 1 subject. Meaning you should point it to **one** subject folder, containing the CT image. The library version is not supposed to work on batch. Kindly let me know how it goes. I will look into the freeze part. I assume it's windows?

Cheers,
Lalith

**Comment by HyperionCore** [comment]
@LalithShiyam thank for the remind, the CT dicom images are stored in D:\moosez\img\Falcon1\S1\s1085, I tried  D:\moosez\img\Falcon1\S1\s1085 and D:\moosez\img\Falcon1\S1, neither work, what level should I choose, do I need to manually convert all dicom files to nifti first?

**Comment by LalithShiyam** [comment]
Hi @HyperionCore,
Sorry for not being clear in the readme section. Yes the data should already be in nifti format (.nii or .nii.gz). 

Basically the input directory should just contain the nifti. 

Kindly let me know if it works and thanks for your patience!

**Comment by HyperionCore** [comment]
@LalithShiyam ， sorry for the late reply, yes, it works, I convert dicom into nifti files(*.nii works, *.nii.gz not work) first, and point the input directory to this folder, it works.

**Comment by Keyn34** [comment]
@HyperionCore, that is a bit strange, *.nii.gz certainly does work. I use it all the time like this. How did you compress or convert it? 
But it is a good thing that it works with plain nifti for you now :)

**Comment by LalithShiyam** [comment]
Closing this due to inactivity.
